### ISSUE TITLE
Option to leverage environment variables as sources for zzapi variables

### ISSUE THREAD

**Issue by gitblit** [agrostar/zzapi-vscode#10]
I need to share settings between my unit/integration tests and the zzapi tests. My unit/integration tests leverage environment variables set in `.env` files. I would like to re-use those values instead of maintaining multiple sets of settings.

Ideally, it would be convenient to set a zzapi variable (in `zzv` or `zzb`) from a process environment variable.

Perhaps something like this?

**envs.zzv**
```
local:
  apiUrl: $env.API_URL
  apiToken: $env.API_TOKEN
```

**Comment by vasan-agrostar** [comment]
This can be done, but I would prefer not to forcibly load the `.env` files using the `dotenv` module. If there are environment variables, we can use them, though. The way you would then load these variables will depend on the tool you are using:

* zzapi-vscode: Is there an extension that can do this?
* zzapi-cli: export the env variables before calling zzapi-cli

 Needs more thought.

**Comment by gitblit** [comment]
I agree with not depending on `dotenv` or loading `.env` files. Node >= 20.6 and bun both have internal support for `.env` files. My objective would be to have a short-hand syntax to access `process.env.MY_VAR`.

**Comment by vasan-agrostar** [comment]
Aligned. But we will need some more corner case handling:

1. Ability to specify the value is indeed `$env.something` and not to be interpreted as an env variable. A very rare use case but we need to address it.
2. How to interpret undefined values.

Proposal:

For 1:
(a)
```
export API_URL=https://example.com
local:
  apiUrl: $env.API_URL # -> https://example.com
  notInterpreted: $$env.LiteralValue # -> $env.LiteralValue
  needDoubleDollar: $$$env.LiteralValue # -> $$env.LiteralValue
```
This can get complicated ... what about quad dollar?

(b)
```
export API_URL=https://example.com
local:
  apiUrl: $env.API_URL # -> https://example.com
  notInterpreted: \$env.LiteralValue # -> $env.LiteralValue
  needBackslash: \\$env.LiteralValue # -> \$env.LiteralValue
```
Again, gets complicated ... what about `\\` and `\\\` etc.

(c)
```
export API_URL=https://example.com
local:
  _options:
    expandEnv: false
  apiUrl: $env.API_URL # -> $env.API_URL
other:
  apiUrl: $env.API_URL # -> https://example.com
```
(d)
Invert the $ usage:
```
export API_URL=https://example.com
local:
  apiUrl($env): API_URL # apiUrl -> https://example.com
  notInterpreted: $env.API_URL # notInterpreted -> $env.API_URL
```
Works but very unintuitive

(e)
Sorry, you can't have $env. at the beginning of a variable value. Deal with it at the point of usage, if you really need it. Or, define an env variable with that value ;-)

For 2:

We will deal with undefined environment variables same as undefined variables themselves.

@gitblit : thoughts?

**Comment by gitblit** [comment]
## 1
I anticipate the need to specify `$env.some_value` as a literal is unlikely. Having said that, I think `$$` escaping is sufficient; I don't think it's worth covering every possible scenario we might conceive until someone raises an issue for that.

To stimulate further ideas, can we differentiate these two cases?

```yaml
local:
  apiUrl: $env.API_URL # -> https://example.com
  notInterpreted: "$env.LiteralValue" # -> $env.LiteralValue
```

## 2
>We will deal with undefined environment variables same as undefined variables themselves.

👍
