### ISSUE TITLE
Alternative syntax for partial equality/matching?

### ISSUE THREAD

**Issue by gitblit** [agrostar/zzapi-vscode#11]
I'd like to match an object on partial equality, not absolute equality.

```yaml
tests:
  $.items: { $exists: true, $type: array, $size: { $gte: 5 } }
  $.items[0]:
    $matches: # $satisfies:
      id: 1
      name: Ethel
```

Where `$.items[0]` returns an object with many properties/fields.

I know I could write this brute-force like this:
```yaml
  $.items[0].id: 1
  $.items[0].name: Ethel
```

I am imagining some complex JSONPath expressions that would be ugly to repeat with the brute-force approach.

**Comment by vasan-agrostar** [comment]
It will indeed be a good convenience, and avoid repetition (and therefore errors) when testing against deeply nested objects. But I'd like to generalize as well as use the same syntax for sub-objects, and be able to nest them infinitely.

```
tests:
  $.items: { $exists: true, $type: array, $size: { $gte: 5 } }
  $.items[0]:
    $tests: 
      $.id: 1
      $.name: Ethel
      $.address:
        $tests:
          $.city: New York
```
Achieves the original objective plus reuses the same test pattern as the root object on sub-objects.
